metadata:
  siteName: SIMKAH Tools
  description: 'Informasi Simkah dan Tool Pendukung Lainnya '
ads:
  isActive: true
  adClient: ca-pub-4364585406937180
  homeAd: '4299515269'
  postAd: '8047188582'
  toolsAd: '4156080424'
  customInjectedHeader: >-
    <meta name="profiton-domain-verification"
    content="50382d253cb280faf75095f4c840222162836e8c38822978e97020858016140c"
    /><meta name="google-adsense-account" content="ca-pub-4364585406937180">
analytics:
  googleAnalyticsId: G-T8WFN21XTC
footer:
  profile: >-
    simkah.web.id bukan web official Kemenag, hadir meneruskan, menyampaikan
    dalam rangka melengkapi informasi dan hal lain untuk Penghulu, Operator
    Simkah dan Calon Pengantin dan masyarakat luas. 
  address: |-
    Kel. Mulya asri
    Kec. Tulang Bawang Tengah
    Kab. Tulang Bawang Barat
  whatsapp: '6285228890161'
  telegram: https://t.me/sigitmanto
  facebook: https://facebook.com/cakwied/
